### PR TITLE
Compare with new_modules_pbd562 branch of penguian/oasis3-mct

### PR DESCRIPTION
**Pull request by penguian**
The purpose of this pull request is to bring to your attention a comparison between the `access-esm1.5` branch of https://github.com/ACCESS-NRI/oasis3-mct and the `new_modules_pbd562` branch of https://github.com/penguian/oasis3-mct

The latter branch is based on [coecms/oasis3-mct/new_modules](https://github.com/coecms/oasis3-mct/tree/new_modules), with the following changes: https://github.com/penguian/oasis3-mct/compare/master...new_modules_pbd562

### CODE REVIEW

**Comment by penguian** [comment]
See the line
```
	git clone -b new_modules https://github.com/coecms/oasis3-mct.git $@
```
in https://github.com/coecms/access-esm-build-gadi/blob/master/Makefile 
for the reason why this branch and repository is used in the pull request: https://github.com/penguian/oasis3-mct/pull/1

**Comment by aidanheerdegen** [comment]
I just have a technical query as to why the PR includes all the commits from the COSIMA OASIS3-mct repo. Holger's changes are after this commit

https://github.com/COSIMA/oasis3-mct/commit/e93d8bcd744abaff7567ea1dbeddecbadf1bbb2d

Some of Holger's commits I'm not sure we'd want anyway, e.g. these both reference specific paths in Holger's directories to a filesystem that no longer exists:

https://github.com/coecms/oasis3-mct/commit/198fa108d8b057da3aa1868951d69fa11f64f48c

https://github.com/coecms/oasis3-mct/commit/dd3cb1379e7f5f1d2f73643c501a177a9b712c24

and this one seems to have mushed together a bunch of commits, so losing the atomic commit history

https://github.com/coecms/oasis3-mct/commit/89cf360ffa02e662d831a29053de668adeb03107

**Comment by penguian** [comment]
Re-open, but change PR to ask to merge with `access-esm1.5-new-modules`.

**Comment by penguian** [comment]
Re-open, but change PR to ask to merge with access-esm1.5-new-modules.

**Comment by penguian** [comment]
Merge. Remove the old `access-esm1.5` branch after the merge.

**Comment by penguian** [comment]
@aidanheerdegen See my comments to Issue #2

**Comment by harshula** [comment]
Hi @penguian , Do you want `access-esm1.5` and `access-esm1.5-new-modules` to be at Commit 0191bf613eb29870eaddd673970918176568fd26 ?

**Comment by penguian** [comment]
@harshula The branch that I want to merge to is called `access-esm1.5-new-modules`. The `access-esm1.5` branch can be deleted again.

**Comment by harshula** [comment]
Hi @penguian , Do you want `access-esm1.5-new-modules` to be at Commit https://github.com/ACCESS-NRI/oasis3-mct/commit/0191bf613eb29870eaddd673970918176568fd26 ?

**Comment by penguian** [comment]
> Hi @penguian , Do you want `access-esm1.5-new-modules` to be at Commit [0191bf6](https://github.com/ACCESS-NRI/oasis3-mct/commit/0191bf613eb29870eaddd673970918176568fd26) ?

It wasn't my original intention, but I see your point. Let's try that, then merge [penguian:new_modules_pbd562](https://github.com/penguian/oasis3-mct/tree/new_modules_pbd562) into it and then test that the resulting reproduces the same way as [penguian:new_modules_pbd562](https://github.com/penguian/oasis3-mct/tree/new_modules_pbd562).

**Comment by penguian** [comment]
OK. Let's try as clean as possible and use commit https://github.com/ACCESS-NRI/oasis3-mct/commit/0e552e4b7cf3c3ef30dad17e46747dc23d8f0f59

**Comment by penguian** [comment]
@harshula Will you do the merge now, or can I do it?

**Comment by harshula** [comment]
Hi @aidanheerdegen , The branch `access-esm1.5-new-modules` has now been branched off `master`. Then Holger's changes from `coecms:new_modules` have been merged into `access-esm1.5-new-modules`. The next step is to merge Paul changes in this PR. Is that better/easier?

**Comment by harshula** [comment]
Hi @aidanheerdegen , The branch `access-esm1.5-new-modules` has now been branched off `master`. Then Holger's changes from `coecms:new_modules` have been merged into `access-esm1.5-new-modules`. The next step is to merge Paul changes in this PR. Is that better/easier? Paul can add changes to Holger's commits in this PR.

**Comment by aidanheerdegen** [comment]
Yes that seems much cleaner and clearer from a review point of view. 

To my mind Holger's changes will have very little bearing on what we want to do, as they're just about picking up different dependency versions and referencing a makefile snippet that no longer exists at that location.

It might even be easier to just branch from `master` and incorporate any of Holger's changes into the `spack` package definition directly, but your decision @penguian.

**Comment by harshula** [comment]
For the first iteration, my strong preference is to use the exact same source code base as the legacy build system.

**Comment by penguian** [comment]
@aidanheerdegen Where are we with this review? Should the changes be merged in?

**Review by harshula — APPROVED** [review]
Reviewed via VC

**Comment by penguian** [comment]
Merging.

**Pull request merged**
