### PR TITLE
Create docker container for CI builds

### LINKED ISSUE #7: Compile complete list of build dependencies

### PR DESCRIPTION
**Pull request by echus**
Closes #7 , #6

### CODE REVIEW

**Comment by echus** [comment]
Looks like it successfully builds but technically "fails" due to an irrelevant error code. We'll need a way of determining whether a build is successful without relying on the build command output.

**Comment by aidanheerdegen** [comment]
> Looks like it successfully builds but technically "fails" due to an irrelevant error code. We'll need a way of determining whether a build is successful without relying on the build command output.

Might be a waste of time to worry too much about `build.sh` as this is just an intermediate step. If the draft version @harshula has made works either pull it in from the branch, or we can merge it

https://github.com/ACCESS-NRI/spack_packages/commit/d2b0a47079ca6ad152618d444bd4540ada0557c6

**Comment by echus** [comment]
@harshula is the draft spec usable at the moment? I'll use it in the container if so.

I think we still need a robust way of checking whether a build is successful for CI purposes without relying entirely on the build script/build tool.

**Comment by harshula** [comment]
@echus Yes, https://github.com/ACCESS-NRI/spack_packages/blob/main/packages/oasis3-mct/package.py is ready to use. Please let me know if there's any problems. At the moment it does still call the "build.sh" directly, but that will need to change.

**Comment by harshula** [comment]
> build command output.
@echus , Are you referring to "build.sh" output or something else?

**Comment by echus** [comment]
@harshula thanks! And yep, build.sh output.

**Comment by harshula** [comment]
@echus , What's the error code number and error string?

**Comment by echus** [comment]
@harshula it's 2. Couldn't find the responsible error string. Only noticed as the docker build process failed on it.

**Comment by harshula** [comment]
`#define ENOENT           2      /* No such file or directory */`

**Comment by echus** [comment]
@harshula ah, thanks. Looks like it can't find the "pio" lib. The last mention of it in the changelog from 2011 says: `- turn off pio build and use of pio lib`. Are these old references that need to be removed? @aidanheerdegen do you have any insight?

**Comment by aidanheerdegen** [comment]
Those are pretty old messages, I would say irrelevant. If it can't find the `pio` library then I'd speculate that part of the build failed, and there is an earlier log message with something more useful in the way of error messages.

**Comment by echus** [comment]
Looks like we're getting the same missing `pio` error in the spack logs using @harshula 's package definition. I'll ignore it for now, assuming it will be fixed when build.sh is replaced.

**Comment by harshula** [comment]
@echus What is the error string that is printed regarding `pio`?

It is possible that the ENOENT is because the makefile includes `build/lib/pio` directory that doesn't exist. Try:
```
diff --git a/util/make_dir/make.ubuntu b/util/make_dir/make.ubuntu
index d96b523..644f2a1 100644
--- a/util/make_dir/make.ubuntu
+++ b/util/make_dir/make.ubuntu
@@ -54,7 +54,7 @@ BINDIR          = $(ARCHDIR)/bin
 # LIBBUILD      : contains a directory for each library
 LIBBUILD        = $(ARCHDIR)/build/lib
 # INCPSMILE     : includes all *o and *mod for each library
-INCPSMILE       = -I$(LIBBUILD)/psmile.$(CHAN) -I$(LIBBUILD)/pio  -I$(LIBBUILD)/mct 
+INCPSMILE       = -I$(LIBBUILD)/psmile.$(CHAN) -I$(LIBBUILD)/mct 
 
 F90FLAGS  = $(F90FLAGS_1) $(INCPSMILE) $(CPPDEF) -I$(NETCDF_INCLUDE)
 f90FLAGS  = $(f90FLAGS_1) $(INCPSMILE) $(CPPDEF) -I$(NETCDF_INCLUDE)
```

**Comment by echus** [comment]
For reference - an example of the PIO error @harshula (from [here](https://github.com/ACCESS-NRI/oasis3-mct/actions/runs/3700828828/jobs/6269599485)

`f951: Warning: Nonexistent include directory '/tmp/root/spack-stage/spack-stage-oasis3-mct-5e57b1aa40840adb6d6747d475dabadab5d9d6fb-bcyp74qyudxsomj7dcrmhdke5vxw3lnr/spack-src/compile_oa3-mct/build/lib/pio' [-Wmissing-include-dirs]`

**Pull request merged**
